name: pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Localization
  intl: ^0.18.0

  # Fonts
  google_fonts: ^5.1.0

  # API
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1

  # UI
  shimmer: ^3.0.0
  cupertino_icons: ^1.0.2

  # Cache
  cached_network_image: ^3.2.3

  # Utils
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

# Splash
flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/images/ic_logo.png"